-- Profiles
create table if not exists profiles (
  id uuid primary key,
  phone text unique,
  display_name text,
  created_at timestamp with time zone default now()
);

-- Credentials table (your chosen name)
create table if not exists passkey_credentials (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  credential_id text unique not null,
  public_key bytea,
  counter bigint not null default 0,
  transports text[],
  created_at timestamp with time zone default now()
);

-- Challenge store
create table if not exists webauthn_challenge_store (
  id bigint generated by default as identity primary key,
  user_id uuid,
  challenge text not null,
  purpose text not null check (purpose in ('registration','authentication')),
  created_at timestamp with time zone default now()
);

create index if not exists idx_profiles_phone on profiles(phone);
create index if not exists idx_passkey_credentials_user on passkey_credentials(user_id);
create index if not exists idx_webauthn_challenge_user on webauthn_challenge_store(user_id);
create index if not exists idx_webauthn_challenge_purpose on webauthn_challenge_store(purpose);
